FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY drizzle.config.ts ./
COPY src/lib/schema.ts ./src/lib/

CMD ["sh", "-c", "echo 'DATABASE_URL: $DATABASE_URL' && pnpm db:push"]
